name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build and publish
        run: ./gradlew publish --stacktrace
        env:
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
